### ISSUE TITLE
Kotlin Vert.x boilerplate

### ISSUE THREAD

**Issue by kanzitelli** [vert-x3/vertx-awesome#116]
Hello!

I would like to know if it makes sense to publish a [boilerplate for Vert.x in Kotlin](https://github.com/kanzitelli/kotlin-vertx-boilerplate) here and if yes then under which section 🤔 The reason why I have done it is when I have been starting with Vert.x in Kotlin I was not able to find anything related to it (except of vertx-examples) and decided to write a small boilerplate by my own. So it might me helpful for beginners 🙂 plus: I already use it successfully in two of my projects

Thanks. All the best 🙌

**Comment by vietj** [comment]
how about making it part of the vertx-starter ?

https://github.com/vert-x3/vertx-starter

**Comment by kanzitelli** [comment]
@vietj I will definitely take a look at it. Thank you for Vert.x 🙌
