### ISSUE TITLE
ORM is missing

### ISSUE THREAD

**Issue by ORESoftware** [vert-x3/vertx-awesome#141]
I would have expected an ORM to make this list - an ORM for Postgres or whatever relational DB.

Perhaps vertx has an in-house ORM so there is no "userland" one?

**Comment by tsegismont** [comment]
There is no in-house ORM and I am not aware of a non-blocking/reactive Java ORM.

JOOQ is not really an ORM but if you're only looking for help with every day SQL, you can take a look at [vertx-jooq](https://github.com/jklingsporn/vertx-jooq/).

**Comment by ORESoftware** [comment]
Yeah after more due diligence it appears you're right. There was an example using Spring and executeBlocking, but it seems like retrieving data in a different verticle and then passing the data via the eventBus in order to respond to a request was a performance drain. Which leads me to one of my main questions, why does that example project put the executeBlocking calls in a separate verticle? why not put the executeBlocking calls in the main verticle that handles HTTP requests, that way you don't have to send data via the eventBus in order to respond to an HTTP request?

**Comment by tsegismont** [comment]
I believe I answered your other question in the `vertx-examples` repo.

**Comment by ORESoftware** [comment]
@tsegismont yeah my biggest remaining question - if one verticle is used - I currently assume that all my code running in that verticle is running on 1 thread?

**Comment by tsegismont** [comment]
Standard verticles are assigned a single event loop yes. If you want to scale to all the cores you can deploy multiple instances of your verticle. This is all explained in the documentation. https://vertx.io/docs/vertx-core/java/
