### ISSUE TITLE
Smallrye Mutiny Vert.x bindings

### ISSUE THREAD

**Issue by magicprinc** [vert-x3/vertx-awesome#186]
It is strange not to see Mutiny with Mutiny Vert.x bindings on the list.

https://smallrye.io/smallrye-mutiny-vertx-bindings/
https://smallrye.io/smallrye-mutiny/

It is almost part of the official Vert.x stack ;-)

**Comment by michel-kraemer** [comment]
Thanks for the hint! :-)
