### ISSUE TITLE
Add SmallRye Fault Tolerance

### ISSUE THREAD

**Issue by magicprinc** [vert-x3/vertx-awesome#188]
https://smallrye.io/docs/smallrye-fault-tolerance/6.2.6/reference/asynchronous.html#async-types

https://smallrye.io/docs/smallrye-fault-tolerance/6.2.6/integration/event-loop.html

SmallRye Fault Tolerance supports Vert.x out of box.

**Comment by michel-kraemer** [comment]
Can you submit a PR please? Thanks. 🙂

**Comment by magicprinc** [comment]
@michel-kraemer https://github.com/vert-x3/vertx-awesome/pull/189

**Comment by tsegismont** [comment]
Closed by #189
