### ISSUE TITLE
Set repo description

### ISSUE THREAD

**Issue by michel-kraemer** [vert-x3/vertx-awesome#62]
I'm currently trying to improve this list to make it comply to the requirements from the awesome project. There is an open pull request containing some instructions:
https://github.com/sindresorhus/awesome/pull/700

I will work on the points, but there is one that I cannot do myself. The repo doesn't have a description.

Can someone who has the right permissions please set a description? Something like the following would be appropriate:

     A curated list of Vert.x resources and projects

Or maybe

    A curated list of awesome Vert.x resources, libraries, and other nice things.

You may also set the repo's URL to

    https://github.com/vert-x3/vertx-awesome

Thanks!
Michel

**Comment by vietj** [comment]
done
